name: myperro
description: "MyPerro - Pet Safety & Tracking App with Smart Collar Integration"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # UI & icons
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  rive: ^0.13.10
  flutter_svg: ^2.2.0
  video_player: ^2.10.0
  url_launcher: ^6.3.2

  # Maps & location
  google_maps_flutter: ^2.10.0
  geolocator: ^12.0.0
  geocoding: ^2.1.1

  # Networking
  http: ^1.2.1
  image_picker: ^1.2.0
  file_picker: ^10.3.2

  # BLE Communication
  flutter_blue_plus: ^1.32.0

  # QR Code Scanning
  mobile_scanner: ^5.0.0

  # State Management
  flutter_riverpod: ^2.5.0

  # Local Storage
  shared_preferences: ^2.2.0

  # Data Models
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0

  # Permissions
  permission_handler: ^11.0.0
  firebase_core: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0

  # Launcher Icon
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/figma/
    - assets/branding/
    - assets/images/
    - assets/videos/
    - assets/animations/
    - assets/illustrations/
    - assets/designs/
    - assets/roles/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/uploaddog.png"
  min_sdk_android: 21
